### ISSUE TITLE
Update PCB so that it can be mounted upside down on a left hand

### ISSUE THREAD

**Issue by reivaxy** [reivaxy/kinetix#7]
Right now some mounting screw holes are to close to components to rest on plastic support if the PCB is placed upside down in a left hand (printed using just a symmetry on the STL)

**Comment by reivaxy** [comment]
3 screws are fine

**Comment by Tomlabroussey2** [comment]
how do i get the motherboard for the hand? is there a tutorial on how to build the hand?

**Comment by reivaxy** [comment]
> how do i get the motherboard for the hand? is there a tutorial on how to build the hand?

Hi Tom, the wiki section has the instruction for building the hand: https://github.com/reivaxy/kinetix/wiki
As for the board, you can order it from JLCPCB as described here: https://github.com/reivaxy/kinetix/wiki/04.ElectronicBoard
You'll still need to solder the components on it.
